name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.reversi.ReversiLab
description: Reversi minigame plugin
author: ucchy
api-version: 1.13

commands:
  reversi:
    description: Commands of ${project.name}
    aliases: [rev]
    usage: |
           /<command> single [easy|normal|hard] - Start a single reversi game.
           /<command> versus (player name) - Send a match request to the specified player.
           /<command> accept - Accept the match request.
           /<command> deny - Deny the match request.
           /<command> cancel - Cancel game.
           /<command> resign - Resign game.
           /<command> spectator (player name) - Join game as spectator.
           /<command> rank [win|lose|played|ratio] [versus|easy|normal|hard] - View ranking data.
           /<command> reload - Reload config data.
    permission: reversilab.command
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  reversilab.command:
    description: Permission of command.
    default: true
  reversilab.single:
    description: Permission of single command.
    default: true
  reversilab.versus:
    description: Permission of versus command.
    default: true
  reversilab.accept:
    description: Permission of accept command.
    default: true
  reversilab.deny:
    description: Permission of deny command.
    default: true
  reversilab.cancel:
    description: Permission of cancel command.
    default: true
  reversilab.resign:
    description: Permission of resign command.
    default: true
  reversilab.spectator:
    description: Permission of cancel command.
    default: true
  reversilab.rank:
    description: Permission of rank command.
    default: true
  reversilab.reload:
    description: Permission of reload command.
    default: op

  'reversilab.*':
    description: All of permissions.
    children:
      reversilab.command: true
      reversilab.single: true
      reversilab.versus: true
      reversilab.accept: true
      reversilab.deny: true
      reversilab.cancel: true
      reversilab.resign: true
      reversilab.spectator: true
      reversilab.rank: true
      reversilab.reload: true
